image: node:16.19.0

definitions:
  setNpmConfig: &setNpmConfig export NEXUS_TOKEN_KEY=$(echo $NEXUS_REGISTRY | sed 's/https://g') &&
    npm config set registry $NEXUS_REGISTRY &&
    npm config set email $NEXUS_EMAIL &&
    npm config set $NEXUS_TOKEN_KEY:_auth=$NEXUS_TOKEN &&
    npm config set always-auth true
  preInstalls: &preInstalls npm install -g typescript &&
    npm install -g ts-node &&
    npm install -g aws-cdk@2.79.1
  setProdAwsCreds:
    &setProdAwsCreds export CDK_DEPLOY_ACCOUNT=$PROD_AWS_ACCOUNT &&
    export CDK_DEPLOY_REGION=$PROD_AWS_DEFAULT_REGION &&
    export AWS_DEFAULT_REGION=$PROD_AWS_DEFAULT_REGION &&
    export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID &&
    export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
  setDtsAwsCreds:
    &setDtsAwsCreds export CDK_DEPLOY_ACCOUNT=$DTS_AWS_ACCOUNT &&
    export CDK_DEPLOY_REGION=$DTS_AWS_DEFAULT_REGION &&
    export AWS_DEFAULT_REGION=$DTS_AWS_DEFAULT_REGION &&
    export AWS_ACCESS_KEY_ID=$DTS_AWS_ACCESS_KEY_ID &&
    export AWS_SECRET_ACCESS_KEY=$DTS_AWS_SECRET_ACCESS_KEY

pipelines:
  branches:
    develop:
      - step:
          name: Deploy
          deployment: dev
          services:
            - docker
          script:
            - env | sort
            - *setNpmConfig
            - *preInstalls
            - *setDtsAwsCreds
            - npx @appfire/fuse-cli deploy --version
            - npx @appfire/fuse-cli@1.2.2  deploy --app "pcfj" --stage "prod"
